### ISSUE TITLE
how far is this project / which features are ready?

### ISSUE THREAD

**Issue by apptum** [Wykks/ngx-mapbox-gl#1]
Hey, thanks for your great work!
Just tried and f.e. `trackResize` seems to do nothing and I couldn't get `mgl-geojson-source` to work either :(
A note in the wiki which features are done would be awesome!

**Comment by Wykks** [comment]
Hi ! Thanks for the #1 issue ! :smile: 

Didn't test `trackResize` in particular, I just pass this options down to mapbox-gl. I guess since mapbox-gl is wrapped inside a component, it's messing with mapbox-gl `trackResize` logic. I'll take a look asap !

`mgl-geojson-source` should works fine. All feature listed on the README are implemented.
Docs : https://github.com/Wykks/ngx-mapbox-gl/wiki/API-Documentation

You have lots of example is this directory : https://github.com/Wykks/ngx-mapbox-gl/tree/master/src/app/demo/examples
You can launch them by doing `yarn && yarn start` and then example routes are listed here : https://github.com/Wykks/ngx-mapbox-gl/blob/master/src/app/demo/module.ts

For `mgl-geojson-source` take a look at
https://github.com/Wykks/ngx-mapbox-gl/blob/7ca64a86dea741e2af7fb8ce407c32ef5728d162/src/app/demo/examples/ngx-geojson-line.component.ts 
or 
https://github.com/Wykks/ngx-mapbox-gl/blob/7ca64a86dea741e2af7fb8ce407c32ef5728d162/src/app/demo/examples/geojson-line.component.ts

I'm working on a demo website, it will be a lot easier access to the examples.

**Comment by apptum** [comment]
wow, I must have been half at sleep yesterday - totally missed the examples! Awesome!! 👍  😄 

But another question, two actually:
1: how to bind a popup to different markers dynamically? I tried it like this, but the popup doesn't show.
```
    <ng-container  *ngFor="let feature of projectIdeasGeometries.features">
      <mgl-marker [lngLat]=feature.geometry.coordinates>
        <div (click)="selectedMarker = feature.geometry.coordinates" class="marker">
        </div>
      </mgl-marker>
    </ng-container>
    <mgl-popup [marker]="selectedMarker">
      Hello from marker !
    </mgl-popup>
```

which leads to my second question which is rather general for best practise advice:
2: Which way would you recommend to display some (maybe hundreds) datapoints on a map which need a popup on click? Is it better to set them as featureLayer and `queryRenderedFeatures`to get the clicked feature, or set them as markers (wich leads to problem 1)?

**Comment by Wykks** [comment]
1. Try to add a *ngIf="selectedMarker" on `<mgl-popup>`
2. It's better to use a layer than marker if you can. It's way more performant (no dom).
Use marker only if you really need html for your symbol.
You don't need to use `queryRenderedFeatures`, the `click` output on the `layer` component already to that for you

**Comment by apptum** [comment]
*ngIf on mgl-popup only works once. closing (via 'x' or click anywhere when `closeOnClick=true`) removes the popup and it won't come back. Maybe the same mapbox quirk that makes a popup won't come back when clicking the symbol that showed it again? (the `popup.remove()`before setting a new one resolves that, see below)

But doing it "the old way" works quite nice:
```
    this.popup.popupInstance.remove();
    this.popup.popupInstance.setHTML(message);
    this.popup.popupInstance.setLngLat(coords);
    this.popup.popupInstance.addTo(this.map.mapInstance);
```

oh and (click) on layer is awesome
(- as your whole work here! Thanks for that again, btw. This is THE single best angularN mapbox wrapper! I'll see if we can tip you a beer the next days 👍 )

**Comment by Wykks** [comment]
I see, makes sense. I'll make an example around this use case and maybe change the api.

This lib really need some real world usage, in order to be out of beta :smile:

**Comment by Wykks** [comment]
This should do the job https://github.com/Wykks/ngx-mapbox-gl/commit/7e93c5a47ea68ffc6c9322306fa4d711f72526cf :)
