### ISSUE TITLE
Route Finder

### ISSUE THREAD

**Issue by iusmanali** [Wykks/ngx-mapbox-gl#145]
Hey, thanks for your great work!
I was looking to draw the route on map. Is it implemented yet or not?
@Wykks

**Comment by vamcs** [comment]
You can either use the Mapbox Direction Plugin (https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-directions/) by manually adding the plugin to the map, since this library doesn't have an extension for it or you call the Directions API and create a GeoJSON LineString and draw that on the map by adding a layer.

**Comment by iusmanali** [comment]
> You can either use the Mapbox Direction Plugin (https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-directions/) by manually adding the plugin to the map, since ngx-mapbox-gl doesn't have an "extension" for it or you call the Directions API and create a GeoJSON LineString and draw that on the map by adding a layer.

Thank you for you reply. I have already solved it by drawing GeoJSON LineString
