### ISSUE TITLE
Upgrade to Angular 8

### ISSUE THREAD

**Issue by Carniatto** [Wykks/ngx-mapbox-gl#168]
Hello, there is any plan to upgrade to Angular 8 or workaround to make it run on Angular 8? This is the only package holding my project down on Angular 7

**Comment by robuandrei** [comment]
Hi @Carniatto you can use it in an Angular 8 project. I use it in an Angular 8 app, and I don't have any problem, everything works fine.

**Comment by Carniatto** [comment]
Thanks for the feedback. We're glad to continue using this library.

**Comment by Wykks** [comment]
Yup, v3.x version works fine with Angular 8 (that's why it's allowed in peerDependencies https://github.com/Wykks/ngx-mapbox-gl/blob/v3.x/projects/ngx-mapbox-gl/package.json#L24)

Closing in favor of https://github.com/Wykks/ngx-mapbox-gl/issues/149 if you want a version based on Angular 8 (but it shouldn't matters, until Angular 9).
