### ISSUE TITLE
Angular Universal (SSR) support

### ISSUE THREAD

**Issue by paullryan** [Wykks/ngx-mapbox-gl#17]
I've taken a stab at this a couple of times and at the moment it appears to be mapbox dependent. The best way I found was to not use the typescript helpers for mapbox code and instead just require it after a isPlatformBrowser test but this is contrived. 

I'm not expecting this to be an easy fix but a placeholder here for discussion seems appropriate. 

I have an app that I am doing server side rendering using this library but I have to instantiate a jsdom instance and put it in place for global.window and global.Blob which is squirrely as a number of library check that window or window.document are non-existent to enable their server side code paths.

**Comment by paullryan** [comment]
Oh and I'd expect that the right solution to this is to in someway disable this module when server side but given the way it loads I'm at a loss as to how.

**Comment by Wykks** [comment]
I never played with Angular Universal, so I have no idea :/
You can't `ngIf` `mgl-map` based on whether or not you're on the browser ?

**Comment by paullryan** [comment]
Ya I understand SSR is it's own beast, I'll play with it some-more (I have  project going into a live beta with customers later today that I am using this on). Like I said I have a hack working but want to find a cleaner way so either way I feel I can contribute this solution back to you but just wanted a place holder here, mostly as a reminder to me to do it :).

**Comment by mapsgeek** [comment]
@paullryan  i created a setup today with SSR and mapboxgl running, yes you will need to initialize your map object in a isPlatformBrowser if statment.
otherwise it will throw an error in your server as mapboxgl undefined, but i made this setup by just importing mapboxgl as a 3rd party in my angular-cli.json file not using ngx-mapbox-gl

**Comment by visurel** [comment]
Any updates on this?

**Comment by mapsgeek** [comment]
@visurel i don't see a problem in using Mapboxgl in SSR i have done it myself and it works straight forward, you just need to wrap your map declaration and operations inside an isPlatformBrowser statement  which you can find information about in the official angular docs and also in the Universal repo readme file

**Comment by vijayamurugan** [comment]
@mapsgeek how did you handle the mapbox import in components

**Comment by mapsgeek** [comment]
@vijayamurugan i don't import mapbox in components, i create a service where i
 `import { Map } from 'mapbox-gl'`
then make a method to initiate your map
```
initMap(container) {
    mapboxgl.accessToken = 'your-token';
    this.map = new mapboxgl.Map({
      container: container,
      style: 'your-style'
      zoom: 0,
      center: [0, 0]
    });
  }
```

then from your component create an instance of the service to create a map with this method, then access the map instance through the service.
this way i can access the same map across different components, and also can initiate a new instance if i need to !, in SSR make sure to wrap your component map initiation and all map logic in a `isPlatformBrowser statement`

**Comment by htrex** [comment]
@mapsgeek can you please share a working example somewhere, or provide some more details?

**Comment by mapsgeek** [comment]
@htrex you should do something like this, it should be the skeleton of your map component no matter how do you initialize your map

```
import { Component, PLATFORM_ID, Inject } from '@angular/core';
import { isPlatformBrowser, isPlatformServer } from '@angular/common';
import { MapService } from './map.service';

@Component({
  selector: 'app-map',
  templateUrl: './map.component.html',
  styleUrls: ['./map.component.css']
})
export class MapComponent implements OnInit {

  constructor( 
    public mapservice:MapService,
    @Inject(PLATFORM_ID) private platformId: Object
    ) { }

  ngOnInit() {
      if (isPlatformBrowser(platformId)) {
        // here you can run any browser specific code, like:
        // All your map code should be wrapped inside this If statment
        // follow my previous comment on how to create a centralized map service

        this.mapservice.initMap('map');

       // then you can write all your general map code in that service shared across all of your components
      // this architecture is opinionated based on your need  and your app structure but in general you just 
      // need to import the `isPlatformBrowser` to make things work with SSR
      }
  }
}
```

**Comment by htrex** [comment]
@mapsgeek using your example technique I'm still not able to make it work with SSR.

./map.service needs an `import * as mapboxgl from 'mapbox-gl';` statement.
Injecting the service on the component triggers the error reported below, even if the service is not initialized.
The error seems to manifest as soon as mapbox-gl.js is imported, not after it's initialization.

```
ReferenceError: self is not defined
    at eval (webpack:///./node_modules/mapbox-gl/dist/mapbox-gl.js?:28:4976)
    at define (webpack:///./node_modules/mapbox-gl/dist/mapbox-gl.js?:21:5)
    at eval (webpack:///./node_modules/mapbox-gl/dist/mapbox-gl.js?:32:1)
    at eval (webpack:///./node_modules/mapbox-gl/dist/mapbox-gl.js?:3:26)
    at eval (webpack:///./node_modules/mapbox-gl/dist/mapbox-gl.js?:5:2)
    at Object../node_modules/mapbox-gl/dist/mapbox-gl.js (/home/htrex/webapps/OPR2019/server.js:1847:1)
    at __webpack_require__ (/home/htrex/webapps/OPR2019/server.js:20:30)
    at Object.mapbox-gl (webpack:///./dist-server/main.js?:2538:18)
    at __webpack_require__ (webpack:///./dist-server/main.js?:20:30)
    at Object../src/app/_services/map.service.ts (webpack:///./dist-server/main.js?:132:16)
```

There's any other foundamental step that is missing from your example?

**Comment by htrex** [comment]
I've found that a working solution is described on the first post of this issue, we need to use *require* instead of *import*, like

```
    if (isPlatformBrowser(this.platformId)) {
      const mapboxgl = require('mapbox-gl');
      mapboxgl.accessToken =
      this.map = new mapboxgl.Map({
        container: 'map', // container id
        style: 'mapbox://styles/mapbox/streets-v11',
        center: [-74.50, 40],
        zoom: 9
      });
    }
```
@mapsgeek I'm not sure how you got it to work using an import statement

**Comment by magnolo** [comment]
@htrex hey there. i am also facing the same problems but using a workaround through the tsconfig import paths which points to different locations for browser or server.

i am using ngx-mapbox by now and had to clone the module structure as server side module for this kind of solution. its not pretty but its working for me and i can inject custom stuff on the server side

```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "@map": ["../node_modules/ngx-mapbox-gl"]
    }
  }
}
```
for the tsconfig.app.json

and 
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "baseUrl": "./",
    "paths": {
      "@map": ["./app/modules/ssr/server/map-module"]
    }
  }
}
```
for my tsconfig.server.json

i then import it as 

``` 
import { NgxMapboxGLModule } from '@map';
```

and can use all the components and directives with no problems.
But as i said before, my ssr map module is an exact clone of all the directives and components using the same selector an module names and could very annoying to maintain

Note: This is just some sample code not really tested because i got lot more of this ssr implementations and a straight copy paste of my code would make no sense =P. would be glad if i could help because i also really tried and failed a lot with this. ( ngx-mapboxgl is super awesome, but makes this approach not easier )

at least i got a problem with this solution: I recently made everything lazy loaded in my app and also wanted to lazy load mapbox just when needed. Everything works fine in dev mode but on production build i get runtime errors in the browser when angulars optimization is active. ( no problems when mapbox comes with the main bundle just lazy loading)

hope thats not totally confusing ^^
cheers

**Comment by mapsgeek** [comment]
@htrex sorry i forgot about this part of configuration i actually didn't do any imports for the mapboxgl, i just declare a variable of mapboxgl like

`declare var mapboxgl;`
and in ngOninit you declare` map: mapboxgl.Map`
so you can get typing intellisense when you do anything with the this.map

and in you reference "`../node_modules/mapbox-gl/dist/mapbox-gl.js"`
in your scripts array in angular.json file where you actually import the mapboxgl
