### ISSUE TITLE
setting `[center]` on map affects zoom & vice versa

### ISSUE THREAD

**Issue by apptum** [Wykks/ngx-mapbox-gl#2]
Dynamically changing `this.center` when
```
<mgl-map
...
    [center]="center"
    [zoom[="zoom"
...
```
resets the zoom to inital value - same the other way round.
(can be seen in demo: examples/center-on-symbol.component)

Expected behaviour:
Changing center/zoom shouldn't affect the zoom/center

**Comment by Wykks** [comment]
Thinking a bit more about this, I think this is correct.
Otherwise if the user zoomed the map, but your app need to set the zoom to the same as before, you're kinda stuck (except changing zoom directly using the map instance but that doesn't count).
In react-mapbox-gl it's handled by passing zoom as an array, which allow the app to just change the ref to "force" a zoom change.
I think we can do better in Angular, with two way data binding. I'll try do that

**Comment by apptum** [comment]
I understand you from a technical standpoint. From a UX perspective, I'd expect the map to not zoom when I click a POI - when I have changed the zoom before.
Maybe that could be a solution: If the user has changed zoom / center, keep that on programmatic changes (f.e. click on a poi and center map there) and instead add a new UI element (like the locate me button) to reset to initial values?

**Comment by Wykks** [comment]
Okay, I tried to make it work with two way data binding, but it's a fail.
Let's fallback to the same solution of react-mapbox-gl.
