### ISSUE TITLE
Hash option overrides path

### ISSUE THREAD

**Issue by HighSoftWare96** [Wykks/ngx-mapbox-gl#222]
I've tried to use the `hash` option in the map initialization and it behaves strangely: first the path is something like this: `localhost:4200/mymap`, then, when the map changes and updates, the path is transformed to `localhost:4200/#13/15.44166/20.95256`. Shouldn't it keep the `mymap` in the path or I've not understand the usage of the `hash` option?

**Comment by BergWerkGIS** [comment]
I'm having the same problem.

I traced it to where the hash is calculated: https://github.com/mapbox/mapbox-gl-js/blob/12991995fa1bb62c5ecdb0282c7c142578b897e5/src/ui/hash.js#L137

Because hash calculation [is throttled (delayed)](https://github.com/mapbox/mapbox-gl-js/blob/12991995fa1bb62c5ecdb0282c7c142578b897e5/src/ui/hash.js#L29) it overwrites/removes the correct route after it has been set by Angular.


I tried to fix it by changing `node_modules/mapbox-gl/dist/mapbox-gl.js`
from
```
t.window.history.replaceState(t.window.history.state,"",e);
```
to
```
t.window.history.replaceState(t.window.history.state,"",t.window.location.pathname.split('/').reverse()[0]+e);
```
which results in the expected URL of `localhost:4200/pageone#13/15.44166/20.95256`.

However, navigating to another Angular route (without a map) also results in
`localhost:4200/pagetwo#13/15.44166/20.95256`

Maybe again because of the delayed hash calculation or some other reasons (maybe discarding the map triggers another hash calculation).

Any ideas how to restore the URL to include the Angular route after it has been modified by the hash calculation?

**Comment by HighSoftWare96** [comment]
Setting every parameters to null does not result to changing only the parameters not null in the `replaceState` function?

**Comment by BergWerkGIS** [comment]
Haven't tried setting every parameter to null in hash.js.

I ended up using this code in every component that can be navigated to from the page with the map in order to remove the fragment (hash):

```javascript
import { ActivatedRoute } from "@angular/router";
import { Location } from '@angular/common';

constructor(
  private _activatedRoute: ActivatedRoute
  , private _location: Location
) { }

ngOnInit(): void {
  if (null !== this._activatedRoute.snapshot.fragment) {
    let path = this._activatedRoute.snapshot.url[0].path;
    this._location.replaceState(path);
  }
}
```

To summarize:
* the patch from my previous comment adds the Angular route to the page with the map and hash
* the code in this comment removes the hash from other pages that are visited from the page with the map

**Comment by HighSoftWare96** [comment]
@dmytro-gokun is this resolved?

**Comment by dmytro-gokun** [comment]
@HighSoftWare96 As far I can understand workaround exists + this library is not responsible for this behavior. It's mapbox-gl itself. So, i'm not sure if we need to take any action here, in this library. Correct me, if i'm wrong.
