### ISSUE TITLE
idea: replace yarn with npm

### ISSUE THREAD

**Issue by BernhardRode** [Wykks/ngx-mapbox-gl#27]
What do you think of replacing yarn with npm.

npm is the standard node package manage and imho any library should use it by default :)

**Comment by Wykks** [comment]
I don't get the `package-lock.json` of `npm`. It doesn't really lock anything. When another dev launch `npm install`, it simply update the lock file and install more recent version of deps.
There `npm ci` (http://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable) that actually (finally) handle `package-lock.json` correctly.
But telling a dev to use `npm ci` instead of `npm install` is a bit weird, and for yarn it's just `yarn`.
Yarn release a also more stable, it just works. npm tend to break stuff between release.

**Comment by BernhardRode** [comment]
Ok ;)
