### ISSUE TITLE
map pin bound to dynamic coordinates is not updating its position

### ISSUE THREAD

**Issue by rohanrichards** [Wykks/ngx-mapbox-gl#33]
The title describes fairly accurately what I'm experiencing. I would like to be able to click on a map and have a map marker move to that location.

Here's my template:
```
	<mgl-map class=""
		[style]="'mapbox://styles/mapbox/streets-v9'"
		[zoom]="[9]"
		[center]="[153.021072, -27.470125]"
		(click)="mapClick($event)"
		>
		<mgl-marker
  			[feature]="pickerLocation"
		>
	  		<div
				(click)="alert('Foo')"
				class="marker"
	  		>
				<i class="fa fa-map-marker"></i>
				{{pickerLocation.geometry.coordinates}}
	  		</div>
		</mgl-marker>
	</mgl-map>
```

Here's the important bits from my controller:
```
	pickerLocation = {
		type: "Feature",
		geometry: {
			type: "Point",
			coordinates: [153.021072, -27.470125]
		}
	};

	mapClick(event) {
		if(event.lngLat){
			this.pickerLocation.geometry.coordinates = event.lngLat;
		}
		console.log(this.pickerLocation);
	}
```

When I click on the map the object coordinates property is being updated, this can be confirmed by seeing the template binding `{{pickerLocation.geometry.coordinates}}` updating, however the markers position isn't changing at all.

I've tried replacing the mgl-marker data source to a plain array or object, instead of a Feature. However this is having the same effect (the pin doesn't move on click).

**Comment by Wykks** [comment]
Hi!

You need to change the ref of `pickerLocation` when you change anything inside.

`ngx-mapbox-gl` doesn't do deep check in every tick. It's too expensive.

**Comment by Wykks** [comment]
You can't just mutate the object. By changing the ref, I mean that you have to create a new object. For example like that in es6 : `{...pickerLocation}`. `ngOnChanges` is only called when references changes, not on object mutation.

`mglDraggable` only works with a `mgl-layer` using `mgl-geojson-source`. Just like in this example: .

https://www.mapbox.com/mapbox-gl-js/example/drag-a-point/

But it's doesn't work well (that's why it's undocumented). (https://github.com/mapbox/mapbox-gl-js/issues/5187)

Draggin a Marker seems a better option that dragging a layer (also see https://github.com/mapbox/mapbox-gl-js/issues/3087)
So, I think I'll move `mglDraggable` to Marker instead of Layer.

You should be able to implement that yourself. Just listen to 'mouseenter' => 'mousedown' => 'mousemove'  and update the coord of the marker at 'mouseup'.

**Comment by Wykks** [comment]
Most of the event are the `mgl-map`, but you can find some event in `mgl-layer` too (https://github.com/Wykks/ngx-mapbox-gl/wiki/API-Documentation#outputs-1)
I don't know If more event are necessary, for now :upside_down_face: . You can open a new issue if you think that an event is missing :)

**Comment by Wykks** [comment]
`mglDraggable` now support `mglMarker` :smiley: (https://github.com/Wykks/ngx-mapbox-gl/commit/8aa02a89af6721d93f7aeb32b42a001ba3408d16)
