### ISSUE TITLE
Angular 18 Support

### ISSUE THREAD

**Issue by nicolaric-akenza** [Wykks/ngx-mapbox-gl#417]
We'd like to upgrade to Angular 18, but there is a peer dependency of ngx-mapbox-gl, which doesn't allow that. can this peer dependency be changed?

**Comment by YeomansIII** [comment]
Please allow me to introduce you to...

✨package.json overrides✨

Never worry about conflicting peer dependencies again!
Introduced in December 2021, overrides allow you to override the version your dependencies' dependencies!

https://docs.npmjs.com/cli/v10/configuring-npm/package-json#overrides

**Comment by nicolaric-akenza** [comment]
@YeomansIII thanks for your kind comment. we now moved on to https://github.com/maplibre/ngx-maplibre-gl, as it is more up to date with the versions😄.

**Comment by dnldpavlik** [comment]
Yeah, that doesn't work. It would be nice if the library would either update the supported version of Angular, or state that it is no longer under development and to find a different library as this is something that will cause issues with others and lead to great frustration down the road.

**Comment by YeomansIII** [comment]
Are still receiving a dependency error? Applying the override allows me to install my dependencies on Angular 18 without any errors or having to do a force install.

**Comment by dnldpavlik** [comment]
I have not tried that configuration, but I was able to get it to install the legacy peer deps flag, but when I try running my application with the library I get an exception that has been seen in Angular 17 (see below) 

the irony for me is that I did not see this error after I had upgraded to Angular 17, only with Angular 18. So now I have to get this error resolved, and it looking like I just need to have a fork that I maintain internally because no one else will make these changes or accept the ones that have been made.

[ERROR] Cannot assign to import "baseApiUrl" node_modules/ngx-mapbox-gl/fesm2022/ngx-mapbox-gl.mjs:100:17: 100 │ MapboxGl.baseApiUrl = options.customMapboxApiUrl; ╵ ~~~~~~~~~~ Imports are immutable in JavaScript. To modify the value of this import, you must export a setter function in the imported file (e.g. "setBaseApiUrl") and then import and call that function here instead. \mapbox-dashboard-test\node_modules\vite\node_modules\esbuild\lib\main.js:1649 let error = new Error(`${text}${summary}`); ^ Error: Build failed with 1 error: node_modules/ngx-mapbox-gl/fesm2022/ngx-mapbox-gl.mjs:100:17: ERROR: Cannot assign to import "baseApiUrl"

**Comment by YeomansIII** [comment]
Can you give a small snippet showing how you are importing MapboxGl and where you are trying to set `baseApiUrl`? There may just be a JS/TS solution to that problem

**Comment by dnldpavlik** [comment]
I could, but I am not using it in the one application. It is part of my library and just throwing the error.  

The only solution I had seen was here, and it was to comment out the code in this library. I will be looking more into on Monday.

**Comment by YeomansIII** [comment]
Good luck. I'm just a user of this lib, but happy to help

**Comment by Skeamy876** [comment]
any headway or workaround with the baseApiUrl Error?

**Comment by dnldpavlik** [comment]
Only solution I had found is what was documented in the issue about Angular 17 issue. I applied the same "patch" and it works so far. 

My attempts to upgrade this library to Angular 18 has more work needed, especially since nx doesn't seem to support Angular 18 yet, as this library uses nx to manage the workspace.

**Comment by nicolaric-akenza** [comment]
@dnldpavlik Nx does support Angular 18 with Nx v19.

**Comment by dnldpavlik** [comment]
Interesting, when I tried nx migrate it didn't Migrated to Angular 18, just 17. I guess I am missing a something
