### ISSUE TITLE
Clusters - Marker options

### ISSUE THREAD

**Issue by guidodizi** [Wykks/ngx-mapbox-gl#52]
I'm trying to use the `<mgl-marker-cluster>` and set the markers in it with anchor and offset options. Is this posible?

**Comment by Wykks** [comment]
Hi!

No, in order to shorten the cluster markup I choosed to automatically render as marker stuff inside `mglPoint` and `mglClusterPoint`. I believe that anchor and offset can be adressed with css.
But! I should be able to improve that.
Currently we have:
```
      <ng-template mglPoint let-feature>
        Marker!
      </ng-template>
      <ng-template mglClusterPoint let-feature>
        Cluster!
      </ng-template>
```
I should be able to _optionnally_ accept that as well.
```
      <ng-template mglPoint let-feature>
            <mgl-marker>
              Marker!
            </mgl-marker>
      </ng-template>
      <ng-template mglClusterPoint let-feature>
            <mgl-marker>
              Cluster!
            </mgl-marker>
      </ng-template>
```
It was mandatory to do that in the first implementation, but that's too verbose. What do you think?

**Comment by guidodizi** [comment]
I fixed it with CSS by applying the corresponding transform on the markers. 

I believe that improvement should be made since it gives the customization of using the already implemented features on `<mgl-marker>`

**Comment by HarelM** [comment]
@guidodizi Can you share your workaround? something like `transfrom: translate(0, -50%)`?
@Wykks was this implemented already by any chance?
I would like to have this option too.
