### ISSUE TITLE
bug in popup with closeOnClick

### ISSUE THREAD

**Issue by apptum** [Wykks/ngx-mapbox-gl#8]
as can be seen in examples/ngx-popup-for-layer
click a symbol to open popup. Click another symbol - the popup is removed but not opened again.

Probably this Mapbox issue: https://github.com/mapbox/mapbox-gl-js/issues/2395

**Comment by Wykks** [comment]
Hi ! Sorry for being late on this (didn't have the time to work on the lib)

That's interesting, I'm not sure how to solve this in the lib.
In the demo, when you click on another symbol, the `mgl-popup` will close (because of `closeOnClick`), and we just change the `selectedPoint` value, but this instance is already closed, hence this bug.
In the demo of mapbox-gl (https://www.mapbox.com/mapbox-gl-js/example/popup-on-click/), when you click on another symbol, there is two instance of popup running for this instant. The one closing and the one opening.

I fixed the demo instead, by forcing Angular to remove the popup before changing the coords. I think, this is better than having two `mgl-popup` in the template. Hope that it's good enough for you ! :)
