### ISSUE TITLE
fitBounds of layer

### ISSUE THREAD

**Issue by BernhardRode** [Wykks/ngx-mapbox-gl#9]
First of all, thanks for the library, it made my day!

I need to update a geojson layer and fit it's bounds, when new data arrived.

Do you think there is a simple way to achieve this?

**Comment by Wykks** [comment]
Hi !

If your geojson it's not very big, after fetching geojson data with the HttpClient, you can use http://turfjs.org/Docs#bbox to calculte the bbox or http://turfjs.org/Docs#center for the center.

If your geojson is big then pass the url to `mgl-geojson-source` (`data` input), because mapbox-gl use a web worker to process it without blocking the ui. And then you must be able to get the bbox/center of this geojson from the server (there maybe a better way than doing this, not sure in this case).

Then, finally, pass that to `fitBounds`/`center` input of the `mgl-map`.

**Comment by BernhardRode** [comment]
Hm...

cannot get it to fitBounds...

inside my  component i have: 
`<mgl-map .... [fitBounds]="bounds"></mgl-map>`

Now when new data arrives, i have:
`this.bounds = [[-73.9876, 40.7661], [-73.9397, 40.8002]];`

but the map is not moving :( 

Maybe you (@Wykks) can help me out.

**Comment by Wykks** [comment]
It's totally a fail from me...
`fitbounds` input does nothing :man_facepalming: 
I'm sure I've handled fitbounds somewhere. But not in ngx-mapbox-gl.
Sorry about that, will fix asap !

**Comment by Wykks** [comment]
Fixed in `v1.0.0-beta.3` :)

**Comment by BernhardRode** [comment]
You are great! Thank you.

**Comment by guidodizi** [comment]
Hi @Wykks ! Great libary.

I'm having troubles with fitBounds too. The thing is, after a click, i apply fitBounds as so
`<mgl-map` .... [fitBounds]="bounds"></mgl-map>`

I want to handle the case where after the fitBounds is made, the user zooms out and then can click the button again and zoom to that same bounds. 
My approach was with (zoomEnd) reset my component variable `bounds` to undefined so that when user click button second time, variable changes, and applies fitBounds again.

Problem is that console throws an error:
`TypeError: Cannot read property 'getNorthWest' of undefined`

Maybe inside mgl-map, on fitBounds you should check value before applying `this.map.fitBounds(bound)?`

Thx!
